billsplit/urls.py
from django.conf.urls import patterns, include, url
# from django.conf.urls.defaults import *
import views
from django.contrib import admin
from django.views.static import * 
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    (r'^billsplit/media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^admin/', include(admin.site.urls)),
#    (r'^fbconnect/$', views.index),
	(r'^paypal/$', views.paypal),
    (r'^account/', include('django.contrib.auth.urls')),
#    (r'^login/$', login),
    (r'^register/$',  views.register),

    (r'^home/$', views.display_home),
#    (r'^events/$', views.display_my_events),
    (r'^event/(\d+)/$', views.display_event),
    (r'^event/(\d+)/new_item/$', views.new_item),
#    (r'^(\d+)/list/$', views.display_event_list),
#    (r'^(\d+)/new_item/$', views.new_item),
#    (r'^(\d+)/my_items/$', views.display_my_items),
#    (r'^(\d+)/details/$', views.display_details),
#    (r'^invites/$', views.display_invites),
    (r'^new_event/$', views.new_event),
#    (r'^(\d+)/new_invite/$', views.new_invite),
#    (r'^(\d+)/final/$', views.display_final_list),
#    (r'^(\d+)/checkout/$', views.display_checkout),
#    (r'^(\d+)/pay/$', views.display_pay),
#    (r'^(\d+)/thanks/$', views.display_return),
	(r'^invite/$', views.friend_invite),
	(r'^welcome/new/(\w+)/$', views.friend_accept),
	(r'^welcome/new/$', views.invite_register),
	(r'^welcome/event/(\w+)/$', views.event_accept),
	(r'^event_join/$', views.event_join),
    (r'^event/(\d+)/event_invite/$', views.event_invite),
    (r'^edit_account/$', views.edit_account),
    (r'^my_account/$', views.my_account),
)

urlpatterns += patterns('django.contrib.auth.views',
    (r'^$', 'login'),
    (r'^logout/$', 'logout'),
    (r'^password_change/$',  'password_change', {'post_change_redirect': '/password_change/done/'}),
    (r'^password_change/done/$', 'password_change_done'),
    (r'^reset_password/$', 'password_reset'),
    (r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',  'password_reset_confirm'),
    
)

billsplit/forms.py
from django import forms
from django.core.context_processors import csrf
from django.forms.models import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from models import *


class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(max_length=75)

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email",)

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.username = self.cleaned_data["username"]
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

class UserChangeForm(forms.Form):
    username = forms.CharField(max_length=30, required=True)
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(max_length=75, required=True)


class EventForm(forms.ModelForm):
    name = forms.CharField(max_length=50)
    date = forms.DateTimeField()
    description = forms.CharField(widget=forms.Textarea)
    location = forms.CharField(max_length=50)

    class Meta:
        model = Event
        fields = ("creator", "name", "date", "description", "location",)

    def save(self, commit=True):
        event = super(EventForm, self).save(commit=False)
        event.creator = self.cleaned_data["creator"]
        event.name = self.cleaned_data["name"]
        event.date = self.cleaned_data["date"]
        event.description = self.cleaned_data["description"]
        event.location = self.cleaned_data["location"]
        if commit:
            event.save()
        return event

class ItemForm(forms.ModelForm):
    item_id = forms.IntegerField(required=False)
    item = forms.CharField(max_length=50)
    cost = forms.IntegerField()
    details = forms.CharField(max_length=50, required=False)

    class Meta:
        model = Item
        fields = ("item_id", "creator", "item", "cost", "details",)

    def save(self, commit=True):
        item = super(ItemForm, self).save(commit=False)
        item.item_id = self.cleaned_data["item_id"]
        item.creator = self.cleaned_data["creator"]
        item.item = self.cleaned_data["item"]
        item.cost = self.cleaned_data["cost"]
        item.details = self.cleaned_data["details"]
        if commit:
            item.save()
        return item

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ["created","image"]

class FriendInviteForm(forms.Form):
	name = forms.CharField()
	email = forms.EmailField()

class EventEmailForm(forms.Form):
	event = forms.CharField()
	name = forms.CharField(required=False)
	email = forms.EmailField()

class EventInviteForm(forms.Form):
	event = forms.CharField()
	name = forms.CharField(required=False)
	email = forms.EmailField(required=False)

class ItemScoreForm(forms.Form):
	item = forms.IntegerField()
	score = forms.IntegerField()

class MemberBillForm(forms.ModelForm):
    event = forms.CharField()
    member = forms.CharField()
    net = forms.FloatField()

    class Meta:
        model = MemberBill
        fields = ("event","member","net",)

    def save(self, commit=True):
        bill = super(MemberBillForm, self).save(commit=False)
        bill.event = self.cleaned_data["event"]
        bill.member = self.cleaned_data["member"]
        bill.net = self.cleaned_data["net"]
        if commit:
            bill.save()
        return bill

billsplit/media/templates/main/base.html
<!DOCTYPE HTML>
<html lang="en">
  <head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title> Dolores - {% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- styles -->
	<link href="{{ MEDIA_URL }}templates/main/css/main.css" rel="stylesheet">
  <link href="{{ MEDIA_URL }}templates/main/css/bootstrap/bootstrap.css" rel="stylesheet">
	<link href="{{ MEDIA_URL }}templates/main/css/bootstrap/bootstrap-responsive.css" rel="stylesheet">
  <link type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.23/themes/ui-lightness/jquery-ui.css" rel="Stylesheet" />
  
    <script type="text/javascript" src="{{ MEDIA_URL }}templates/main/js/jquery.js"></script>
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  {% block header %}{% endblock %}
  </head>
  <body>
    {% block fbook %}
        {% endblock %}
    <div class="wrapper">
      <div class="navbar navbar-fixed-top">
          <div class="navbar-inner">
            <div class="container-fluid">
              <a class="brand pagination-centered" id="brand"><h1>dolores</h1></a>
            </div>
          </div>
        </div>
      <div id="main" class="container-fluid">
        {% block content %}
        {% endblock %}
      </div>
    </div>








  <!-- javascript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.23/jquery-ui.min.js"></script>
  <script src="{{ MEDIA_URL }}templates/main/js/bootstrap/bootstrap.js"></script>

  {% block footer %}{% endblock %}

  </body>
</html>

billsplit/media/templates/main/base2.html
<!DOCTYPE HTML>
<html lang="en">
  <head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title> BillSplit - {% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- styles -->
    <link href="{{ MEDIA_URL }}templates/main/images/icon.png" rel="icon" type="image/png">
	<link href="{{ MEDIA_URL }}templates/main/css/main2.css" rel="stylesheet">
  <link href="{{ MEDIA_URL }}templates/main/css/colorbox.css" rel="stylesheet">
  <link type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.23/themes/ui-lightness/jquery-ui.css" rel="Stylesheet" />
  
    <script type="text/javascript" src="{{ MEDIA_URL }}templates/main/js/jquery.js"></script>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-36515913-1', 'auto');
      ga('send', 'pageview');

    </script>
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  {% block header %}{% endblock %}
  </head>
  <body>
    {% block fbook %}
        {% endblock %}
  <div class="nav-bar">
    {% block nav %}
    {% endblock %}
  </div>
  <div id="user-area" class="user-area" style="position:static;">
    <div id="user-events">
      <div class="main">
    {% block content %}
    {% endblock %}
      </div>
    </div>
  </div>


  <!-- javascript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.23/jquery-ui.min.js"></script>
  <script src="https://www.paypalobjects.com/js/external/dg.js"></script>
  <script src="{{ MEDIA_URL }}templates/main/js/bootstrap/bootstrap.js"></script>
  <script src="{{ MEDIA_URL }}templates/main/js/watermarkinput.js"></script>
  <script src="{{ MEDIA_URL }}templates/main/js/colorbox.js"></script>



  {% block footer %}{% endblock %}

  </body>
</html>

billsplit/media/templates/main/event_join.html
{% extends "main/base2.html" %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="open">
        <div class="login-header">
            <img src="{{ MEDIA_URL }}templates/main/images/logo.png"/>
        </div>
        <div class="open-area">
            <div class="event-join-text">
                <h2>You got invited to an event</h2>
                <h3>To join, login or register</h3>
            </div>
            <br />
            <form action="" method="post">
                <div class="form-padding">
                <div class="form-row">
                {% if form.errors %}
                <h2>Your Username or Password was wrong. Try again!</h2>
                <br />
                {% endif %}
                <label for="id_username" class="biglabel"><h4>Username</h4></label> 
                <input id="id_username" type="text" name="login-username" maxlength="30" class="input-row"/>
                </div>
                <div class="form-row">
                <label for="id_password1" class="biglabel"><h4>Password</h4></label> 
                <input type="password" name="login-password" id="id_password" class="input-row"/>
                <input type="hidden" name="login" value="1"/>
                <input type="hidden" name="next" value="/home/"/>
                </div>
                <div class="submit-row"> 
                {% csrf_token %}
                <button type="submit" class="login-button">Login</button>
            </div>
            </form>
        <br />
            <form action="" method="post">
                <div class="form-padding">
                    <div class="form-row">
                {{ register_form.first_name.errors }}
                <label for="id_first_name" class="biglabel"><h4>First Name</h4></label> 
                <input id="id_first_name" type="text" name="first_name" maxlength="30" class="input-row" />
                </div>
                 <div class="form-row">
                {{ register_form.last_name.errors }}
                <label for="id_last_name" class="biglabel"><h4>Last Name</h4></label> 
                <input id="id_last_name" type="text" name="last_name" maxlength="30" class="input-row"/> 
                </div>
                <div class="form-row">
                {{ register_form.username.errors }}
                <label for="id_username" class="biglabel"><h4>Username</h4></label> 
                <input id="id_username" type="text" name="username" maxlength="30" class="input-row"/>
                </div>
                <div class="form-row">
                <span class="helptext"></span>
                {{ register_form.password2.errors }}
                <label for="id_password1" class="biglabel"><h4>Password</h4></label> 
                <input type="password" name="password1" id="id_password1" class="input-row"/>
                </div>
                <div class="form-row">
                <label for="id_password2" class="biglabel"><h4>Confirm</h4></label> 
                <input type="password" name="password2" id="id_password2" class="input-row"/> 
                </div>
                <div class="form-row">
                <span class="helptext"></span>
                {{ register_form.email.errors }}
                <label for="id_email" class="biglabel"><h4>Paypal Email</h4></label> 
                <input id="id_email" type="text" name="email" maxlength="30" class="input-row"/>
                </div>
                <input type="hidden" name="register" value="1"/>
                <div class="submit-row"> 
                {% csrf_token %}
                <button class="register-button" type="submit">Sign me up</button>
            </div>
            </form>
            <br />
            <button onclick="location.href='/'" type="button" class="no-thanks-button">No thanks</button>
    </div>
</div>
{% endblock %}

billsplit/media/templates/main/friend_invite.html
{% extends "main/base.html" %}

{% block title %}Invite A Friend{% endblock %}
{% block head %}Invite A Friend{% endblock %}

{% block content %}
<a id="home" class="btn btn-inverse" href="/home/"><i class="icon-home icon-white"></i> Home</a>
<div class="row-fluid">
	<div id="navigation_area" class="span12 pagination-centered">
		<h1>Invite a friend</h1>
		<form method="post" action=".">

				<label for="id_name"><h4>Name</h4></label> 
				<input id="id_name" type="text" name="name" maxlength="50" />  
				<br />
				<label for="id_email"><h4>Email</h4></label> 
				<input id="id_email" type="text" name="email" maxlength="50" /><br />
				<br />
				{% csrf_token %}
				<button class="btn" type="submit">Send Invite</button>
		</form>
	</div>
</div>
{% endblock %}

billsplit/media/templates/main/home2.html
{% extends "main/homebase.html" %}

{% block title %}Home{% endblock %}

{% block center-header %}
    <div id="welcome-header" class="center-header">
        <h4>Get started</h4>
    </div>
{% endblock %}    
{% block center %}    
    <div class="center-area">
        <div class="center-wrapper">
            <div class="home-wrapper">
                <h3>Welcome to BillSplit</h3>
                <br />
                <h4>Here you'll be able to see all your events and start one of your own!</h4>
                <br />
                <h4>Once you host an event, you can invite friends, add items to bring, and chat.</h4>
                <br />
                <h4>After it's all done, the people who didn't pay enough can pay back their generous friends via PayPal.</h4>
                <br />
                <h4>Let's get started!</h4>
                <br />
                <a href="/new_event/" class="submit-button" type="button">Host an event</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block right %}
{% endblock %}

billsplit/media/templates/main/index.html
{% load fbconnect %}
<html>
<head>
    <!-- JS Files -->
    <script type="text/javascript" src="{{ MEDIA_URL }}templates/main/js/jquery.js"></script>
    {% facebook_login_script %}
    <!-- Document Ready functions -->
    <script type="text/javascript">
        //functions which are done when the document is ready
      $(function(){
          fbconnected(function(){
              // connected to facebook
          },function(){
              // not connected to facebook
              fblogin(fblogin_success,fblogin_fail);
          });
      });
    </script>
    <script type="text/javascript">
    fblogin_success = function(){
        //logged in user
      FB.api('/me', function(response) { 
          $('#name').html(response.name);
          $('#first_name').html(response.first_name);
          $('#last_name').html(response.last_name);
          $('#link').html(response.link);
          $('#birthday').html(response.birthday);
          $('#gender').html(response.gender);
          $('#timezone').html(response.timezone);
          $('#locale').html(response.locale);
          $('#verified').html(''+response.verified);
          $('#updated_time').html(response.updated_time);
          $('#other_information').show();
      });
    }
    fblogin_fail = function(){
          //guest
    }
    </script>
</head>
<body>
    {% facebook_load_script %}
    <div>Hello
    <span id="name">Guest</span>!<br />
    <div id="other_information" style="display: none;">         
        First Name: <span id="first_name"></span><br />
        Last Name: <span id="last_name"></span><br />
        Link: <span id="link"></span><br />
        Birthday: <span id="birthday"></span><br />
        Gender: <span id="gender"></span><br />
        Timezone: <span id="timezone"></span><br />
        Locale: <span id="locale"></span><br />
        Verified: <span id="verified"></span><br />
        Updated Time: <span id="updated_time"></span><br />
    </div>
</div>
</body>
</html>

billsplit/media/templates/main/login2.html
{% extends "main/base2.html" %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="register">
        <div class="register-form">
    {% if user.is_authenticated %}

    <h2>Hey, {{ user.first_name }}.</h2>

    {% endif %}

    {% if form %}
        <div class="register-form-wrapper">
    <form action="" method="post">
        <div class="form-padding">
            <div class="form-row">
        <label for="id_first_name" class="biglabel"><h4>First Name</h4></label> 
        <input id="id_first_name" type="text" name="first_name" maxlength="30" class="input-row"/>
        </div>
         <div lass="form-row">
        <label for="id_last_name" class="biglabel"><h4>Last Name</h4></label> 
        <input id="id_last_name" type="text" name="last_name" maxlength="30" class="input-row"/> 
        </div>
        <div lass="form-row">
        {{ form.username.errors }}
        <label for="id_username" class="biglabel"><h4>Username</h4></label> 
        <input id="id_username" type="text" name="username" maxlength="30" class="input-row"/>
        </div>
        <div lass="form-row">
        <span class="helptext"></span>
        {{ form.password2.errors }}
        <label for="id_password1" class="biglabel"><h4>Password</h4></label> 
        <input type="password" name="password1" id="id_password1" class="input-row"/>
        </div>
        <div lass="form-row">
        <label for="id_password2" class="biglabel"><h4>Password confirmation</h4></label> 
        <input type="password" name="password2" id="id_password2" class="input-row"/> 
        </div>
        <div lass="form-row">
        <span class="helptext"></span>
        {{ form.email.errors }}
        <label for="id_email" class="biglabel"><h4>Email</h4></label> 
        <input id="id_email" type="text" name="email" maxlength="30" class="input-row"/>
        </div>
        <div class="submit-row"> 
        {% csrf_token %}
        <button class="btn btn-inverse" type="submit">Sign me up</button>
    </div>
    </form>
</div>
    {% else %}

    <form action="https://www.sandbox.paypal.com/webapps/adaptivepayment/flow/pay" target="PPDGFrame"> 
        <input id="type" type="hidden" name="expType" value="light"> 
        <input id="paykey" type="hidden" name="paykey" value="{{paykey}}">
        <input type="submit" id="submitBtn" value="Pay with PayPal">    
    </form>
        </div>
    {% endif %}
    </div>
</div>
{% endblock %}

billsplit/media/templates/main/my_account.html
{% extends "main/homebase.html" %}

{% block title %}Home{% endblock %}

{% block center-header %}
    <div id="account-header" class="large-header">
        <h4>Account Details</h4>
    </div>
{% endblock %}    
{% block center %}    
    <div class="center-area">
        <div class="center-wrapper">
            <div id="account-details" class="account-details">
                <div class="form-row">
                    Usernme: <span class="account-detail">{{user.username}}</span>
                </div>
                <div class="form-row">
                    First name: <span class="account-detail">{{user.first_name}}</span>
                </div>
                <div class="form-row">
                    Last name: <span class="account-detail">{{user.last_name}}</span>
                </div>
                <div class="form-row">
                    PayPal Email: <span class="account-detail">{{user.email}}</span>
                </div>
                <br />
                <input id="account-edit-button" class="edit-button" value="Edit" type="submit">
                <br />
                <span class="change-password-button">
                    <a href="/password_change/">Change Password</a>
                </span>
            </div>
            <div id="account-edit-pword" class="account-details initiallyHidden">
                <form method="post" action=".">
                    <div class="form-row">
                        <label for="id_item" class="smalllabel"><h4>What is your password?</h4></label>
                    </div>
                    <input id="id_confirm" type="hidden" name="confirm" maxlength="30" class="input-row" value="confirm" />
                    <input id="id_username" type="hidden" name="username" maxlength="30" class="input-row" value={{user.username}} />
                    <div class="form-row"> 
                        <input id="id_password" type="password" name="password" maxlength="50" class="password"/>
                    </div>
                    <br />
                    {% csrf_token %}
                    <input class="account-edit-pword-button" value="Edit Account" type="submit">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block right %}
{% endblock %}

billsplit/media/templates/main/my_events.html
{% extends "main/base.html" %}

{% block title %}New Event{% endblock %}

{% block content %}
<a id="home" class="btn btn-inverse" href="/home/"><i class="icon-home icon-white"></i> Home</a>
<div class="row-fluid">
	<div id="navigation_area" class="pagination-centered">
	<h2>Your Events</h2>
	<br />
	<br />
	{% for event in events %}
	
	
	<br />
	<div class="btn-group">
	  <button id={{event.id}} class="btn item-button send_button send_{{event.id}}">Send <i class="icon-envelope"></i></button>

	  <span class="initiallyHidden send_done_{{event.id}}">
	  <button id={{event.id}} class="btn btn-inverse item-button send_button ">Don't Send</i></button>
	</span>

	  <a href="/{{event.id}}/" class="btn event-button" type="button">
	  	{{event.name}}
	  	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	  	{{event.creator.first_name}} {{event.creator.last_name}}
	  	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	  	{{event.date|date:"M d, Y" }}
	  	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	  	{{event.location}}</a>
	</div>
<div class="initiallyHidden invite_form_{{event.id}}">
	<div id="new_user_form"	class="half-form">
		<h3>New to dolores</h3>
	<form method="post" action=".">
		<input id="id_event" type="hidden" name="event" value={{event.id}} />

		<label for="id_name"><h4>Name</h4></label> 
		<input id="id_name" type="text" name="name" maxlength="50" />  
				<br />
		<label for="id_email"><h4>Email</h4></label> 
		<input id="id_email" type="text" name="email" maxlength="50" /><br />
		<br />
		{% csrf_token %}
		<button class="btn" type="submit">Send Invite</button>
	</form>
	</div>
	<div id="another_user_form" class="half-form">
		<h3>Already on dolores</h3>
	<form method="post" action=".">
		<input id="id_event" type="hidden" name="event" value={{event}} />

		<label for="id_name"><h4>Name</h4></label> 
		<input id="id_name" type="text" name="user_search" maxlength="50" />  
		<br />
		{% csrf_token %}
		<button class="btn" type="submit">Search</button>
	</form>
</div>
</div>

	{% endfor %}
  </div>
</div>
{% endblock %}


{% block footer %}
<script>
$(document).ready(function(){
  $(".send_button").click(function(){
  	select = $(this);
    id = select.attr('id');
  	$(".send_"+ id).toggle();
  	$(".send_done_"+ id).toggle();
    $(".invite_form_"+ id).toggle();
    });
  });
 </script>
 {% endblock %}

billsplit/media/templates/main/myevents.html
{% extends "main/base.html" %}

{% block title %}New Event{% endblock %}

{% block content %}
<div class="row-fluid">
	<div id="navigation_area" class="span12 pagination-centered">
	<h1> Event</h1>

	<h2>Your Events.</2>

	{% for event in events %}
	<div class="btn-group">
	  <a class="btn">Send</a>
	  <a href="/new_event/" class="btn" type="button">{{event.name}}   {{event.creator}}   {{event.date}}   {{event.location}}</a>
	</div>

  </div>
</div>
{% endblock %}

billsplit/media/templates/main/new_item.html
{% extends "main/homebase.html" %}

{% block title %}Home{% endblock %}


{% block top %}
<div class="event-title">
    <h4>{{event.name}}</h4>
</div>
{% endblock %}
{% block left %}

{% endblock %}
{% block center-header %}

{% endblock %}
{% block center %}

{% endblock %}
{% block right %}
{% endblock %}
            

billsplit/media/templates/main/pay_confirm.html
{% extends "main/homebase.html" %}

{% block title %}Confirm{% endblock %}

{% block center-header %}
    <div id="pay-header" class="center-header">
        <h4>Pay</h4>
    </div>
{% endblock %}
{% block center %}
        <div class="center-area">
        	<div class="center-wrapper">
        		<div class="pay-confirm-wrapper members-paid">
                    <h2>Who you're paying</h2>
                    {% for member, amount in paypalList.items %}
                    <span class="billlabel">{{member.first_name}} {{member.last_name}}</span>
                    <span class="billmoney">${{amount}}</span>
                    {% endfor %}
		    		<form action="https://www.sandbox.paypal.com/webapps/adaptivepayment/flow/pay" target="PPDGFrame">
				        <input id="type" type="hidden" name="expType" value="light"> 
				        <input id="paykey" type="hidden" name="paykey" value="{{paykey}}">
				        <input type="submit" id="submitBtn" class="paypal-button"value="Pay with PayPal">
		    		</form>
                    <br />
                    <h3>Paypal isn't live yet, this is just a testing environment.</h3>
		    	</div>
		    </div>
		</div>
	</div>

{% endblock %}

            

billsplit/media/templates/main/payment_test.html
{% extends "main/base2.html" %}

{% block title %}Pay{% endblock %}

{% block content %}
    <div class="center">
        <div class="center-area">
    {% if user.is_authenticated %}

    <h2>Hey, {{ user.first_name }}.</h2>

    {% endif %}

    {% if form %}
        <div class="register-form-wrapper">
    <form action="" method="post">
        <div class="form-padding">
            <div class="form-row">
        <label for="id_amount" class="biglabel"><h4>Amount</h4></label> 
        <input id="id_amount" type="text" name="amount" maxlength="3" class="input-row"/> 
    </div>
    <div lass="form-row">
        <label for="id_email" class="biglabel"><h4>Email</h4></label> 
        <input id="id_email" type="text" name="email" maxlength="30" class="input-row" /> 
    </div>
        <br />
        {% csrf_token %}
        <div class="submit-row">
        <button class="btn btn-inverse" type="submit">Pay him</button>
        </div>
    </div>
    </form>
</div>
    {% else %}

    <form action="https://www.sandbox.paypal.com/webapps/adaptivepayment/flow/pay" target="PPDGFrame"> 
        <input id="type" type="hidden" name="expType" value="light"> 
        <input id="paykey" type="hidden" name="paykey" value="{{paykey}}">
        <input type="submit" id="submitBtn" value="Pay with PayPal">    
    </form>
        </div>
    {% endif %}
    </div>
</div>
{% endblock %}

{% block footer %}
<script src="https://www.paypalobjects.com/js/external/dg.js"></script>
<script> 
    var dgFlow = new PAYPAL.apps.DGFlow({ trigger: 'submitBtn' }); 
</script>
{% endblock %}